### PR TITLE
Api support

### PR DESCRIPTION
**Pull request by JawadAzizi**
the api.js file works the same as sveltekit +server.js file.
api.js file can export the following methods : get(), post(), put() and del().
each method can support the  corresponding http method.

in order to enable the api response do not send 'u-partial' header. that request is considered as api call.

### CODE REVIEW

**Comment by TheHadiAhmadi** [comment]
Thanks, I'll review tomorrow.

**Comment by TheHadiAhmadi** [comment]
@JawadAzizi 
I prefer https://kit.svelte.dev/docs/form-actions 


what do you think?

**Comment by JawadAzizi** [comment]
> Can you make api support similar to Form Actions?

yes, but i think handling form action in such mannar is php like programming.

**Comment by JawadAzizi** [comment]
i will add the support to run scripts and pass some data to page before the page renders simmilar to +page.server.js in sveltekit, first and then i will add from action as you metioned.

**Comment by TheHadiAhmadi** [comment]
What is the problem of php? :)

**Pull request closed without merging**
